server.port=8080

spring.application.name=employee-service

# =========================
# CONFIG DB
# =========================

spring.datasource.url=jdbc:h2:mem:employee_db
spring.datasource.username=sa
spring.datasource.password=
spring.datasource.driver-class-name=org.h2.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.open-in-view=false
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# =========================
# JACKSON / JSON
# =========================

spring.jackson.deserialization.accept-single-value-as-array=true
spring.jackson.time-zone=America/Mexico_City

# =========================
# SWAGGER / OPENAPI
# =========================

springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs

# =========================
# ACTUATOR
# =========================
management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always
management.info.env.enabled=true

info.app.name=employee-service
info.app.description=API de evaluación técnica
info.app.version=1.0.0
info.app.owner=Luis

# =========================
# LOGS
# =========================

# Nivel general de logs
logging.level.root=INFO

# Logs web de Spring
logging.level.org.springframework.web=INFO

# Logs de SQL ejecutado por Hibernate
logging.level.org.hibernate.SQL=DEBUG